### ISSUE TITLE
测试用例 `lv7/11_complex.c` 可能存在未定义行为

### ISSUE THREAD

**Issue by Guyutongxue** [pku-minic/compiler-dev-test-cases#1]
https://github.com/pku-minic/compiler-dev-test-cases/blob/3b516c7fbe7ae1ab05584292e2c5444a15c075a9/testcases/lv7/11_complex.c#L1-L22

该测试用例中，最外层 `while` 后没有 `return` 语句。如果控制流抵达该循环外（尽管不可能），则返回值是未定义的。

**Comment by MaxXSoft** [comment]
感谢指正! 已修复.
